sonar.projectKey=kubernetes-outage-escape-room
sonar.projectName=Kubernetes Outage Escape Room
sonar.projectVersion=1.0

sonar.sources=backend/src/main/java,backend/src/main/resources,frontend
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.junit.reportPaths=backend/target/surefire-reports

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/data/**,**/*.db,frontend/public/assets/**
sonar.coverage.exclusions=frontend/**,backend/src/main/resources/**,backend/src/main/java/**/dto/**,backend/src/main/java/**/model/**
sonar.sourceEncoding=UTF-8
