apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: outage-escape-room
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_PASSWORD: escape_password
  SPRING_DATASOURCE_PASSWORD: escape_password
