/* data.js — game content & per-biome room themes (window.QuestData).
   Room 1: cause-fix (3 levels). Rooms 2–6: distinct challenge types. */
(function () {
  const ROOM_THEME = {
    forest: { accent: '#4FB23A', base: '#0B2417', scene: 'forest',
      bg: `linear-gradient(180deg, rgba(7,21,13,.02) 0%, rgba(7,21,13,.06) 26%, rgba(7,21,13,.30) 62%, rgba(7,21,13,.50) 100%)` },
    snow: { accent: '#5C87A6', base: '#16273A', scene: 'snow',
      bg: `linear-gradient(180deg, rgba(12,24,38,.02) 0%, rgba(12,24,38,.06) 26%, rgba(12,24,38,.30) 62%, rgba(12,24,38,.52) 100%)` },
    desert: { accent: '#C68A33', base: '#241407', scene: 'desert',
      bg: `linear-gradient(180deg, rgba(28,16,6,.02) 0%, rgba(28,16,6,.06) 26%, rgba(28,16,6,.30) 62%, rgba(28,16,6,.52) 100%)` },
    beach: { accent: '#2E9CA8', base: '#0B2A30', scene: 'beach',
      bg: `linear-gradient(180deg, rgba(7,30,34,.02) 0%, rgba(7,30,34,.06) 26%, rgba(7,30,34,.30) 62%, rgba(7,30,34,.52) 100%)` },
    ice: { accent: '#4C8FB0', base: '#10222F', scene: 'ice',
      bg: `linear-gradient(180deg, rgba(10,22,32,.02) 0%, rgba(10,22,32,.06) 26%, rgba(10,22,32,.30) 62%, rgba(10,22,32,.52) 100%)` },
    volcanic: { accent: '#D45A36', base: '#1A0604', scene: 'volcanic',
      bg: `linear-gradient(180deg, rgba(20,5,3,.04) 0%, rgba(20,5,3,.10) 26%, rgba(20,5,3,.34) 62%, rgba(20,5,3,.56) 100%)` },
  };

  // Room content is loaded from the backend at runtime (generated by scenario_generator.py).
  // App.jsx fetches /api/rooms/{id}/content on startup and populates this object.
  const CONTENT = {};

  const ROLES = ['Debugger', 'Networker', 'SRE', 'Architect'];

  window.QuestData = { ROOM_THEME, CONTENT, ROLES };
})();
