spring.application.name=KubernetesOutageEscapeRoom
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/escape_room_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.open-in-view=false
server.port=${SERVER_PORT:8081}
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=false
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s
